### PR TITLE
Created subtract function

### PR DESCRIPTION
**Pull request by tarimaha**
only added subtract function to code

### CODE REVIEW

**Review by dilonne — COMMENTED** [review]
Your function should print the result of subtraction and it should also print that we are doing subtraction

**Review by dilonne — COMMENTED** [review]
Add a docstring to your function

**Review by dilonne — COMMENTED** [review]
Squash your commits to one original commit

**Review by dilonne — COMMENTED** [review]
You have tried as far as pushing a single commit, however your commit message is off. The only message you should have left is “created subtract function” the rest you should have deleted or commented out

**Review by dilonne — COMMENTED** [review]
Think of it like this, the commit should reflect the relevant and necessary things you did, which is typically the first commit you make, not the other cleanups you did

**Review by dilonne — COMMENTED** [review]
So you’re to edit this commit message to only include the relevant part. Hint there’s p for pick, there’s s for squash, use the one relevant for editing

**Review by dilonne — COMMENTED** [review]
Your final commit has no docstrings, something went wrong with your squashing. See this please => https://github.com/tarimaha/calculator/pull/1#pullrequestreview-1678846003

**Review by dilonne — COMMENTED** [review]
Squash your commits into one commit

**Review by dilonne — COMMENTED** [review]
Still your final commit has no docstring and your commit message is not clean. Please make sure your commit message is exactly this “added subtract functionality”

**Comment by dilonne** [comment]
Why was this closed?

**Comment by dilonne** [comment]
Why was this closed?

**Comment by tarimaha** [comment]
i do no think i have the right to reopen this request

**Pull request closed without merging**
